// <auto-generated />
using System;
using EventEaseVMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventEaseVMS.Migrations
{
    [DbContext(typeof(EventEaseDbContext))]
    [Migration("20260611192237_SeedEventTypes")]
    partial class SeedEventTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEaseVMS.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("VenueId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventEaseVMS.Models.BookingDetailViewModel", b =>
                {
                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("VenueCapacity")
                        .HasColumnType("int");

                    b.Property<string>("VenueImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_BookingDetails", (string)null);
                });

            modelBuilder.Entity("EventEaseVMS.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            EventTypeId = 1,
                            Description = "Business conferences and professional summits",
                            TypeName = "Conference"
                        },
                        new
                        {
                            EventTypeId = 2,
                            Description = "Wedding ceremonies and receptions",
                            TypeName = "Wedding"
                        },
                        new
                        {
                            EventTypeId = 3,
                            Description = "Live music performances and shows",
                            TypeName = "Concert"
                        },
                        new
                        {
                            EventTypeId = 4,
                            Description = "Birthday celebrations and parties",
                            TypeName = "Birthday"
                        },
                        new
                        {
                            EventTypeId = 5,
                            Description = "Team events, award ceremonies, launches",
                            TypeName = "Corporate Function"
                        },
                        new
                        {
                            EventTypeId = 6,
                            Description = "Art shows, trade expos, displays",
                            TypeName = "Exhibition"
                        },
                        new
                        {
                            EventTypeId = 7,
                            Description = "Training sessions and interactive workshops",
                            TypeName = "Workshop"
                        },
                        new
                        {
                            EventTypeId = 8,
                            Description = "Formal dinners and fundraising galas",
                            TypeName = "Gala Dinner"
                        });
                });

            modelBuilder.Entity("EventEaseVMS.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 200,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Johannesburg",
                            VenueName = "Shepstone Gardens"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 500,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Fourways",
                            VenueName = "Montecasino"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 1000,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Sandton",
                            VenueName = "Sandton Convention Centre"
                        },
                        new
                        {
                            VenueId = 4,
                            Capacity = 150,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Muldersdrift",
                            VenueName = "Glenburn Lodge"
                        },
                        new
                        {
                            VenueId = 5,
                            Capacity = 300,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Muldersdrift",
                            VenueName = "Avianto Estate"
                        },
                        new
                        {
                            VenueId = 6,
                            Capacity = 250,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Bryanston",
                            VenueName = "The Forum Bryanston"
                        },
                        new
                        {
                            VenueId = 7,
                            Capacity = 800,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "North West",
                            VenueName = "Sun City Resort"
                        },
                        new
                        {
                            VenueId = 8,
                            Capacity = 400,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Stellenbosch",
                            VenueName = "Spier Wine Farm"
                        },
                        new
                        {
                            VenueId = 9,
                            Capacity = 180,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Umhlanga",
                            VenueName = "The Oyster Box"
                        },
                        new
                        {
                            VenueId = 10,
                            Capacity = 1200,
                            IsActive = true,
                            IsAvailable = true,
                            Location = "Cape Town",
                            VenueName = "CTICC"
                        });
                });

            modelBuilder.Entity("EventEaseVMS.Models.Booking", b =>
                {
                    b.HasOne("EventEaseVMS.Models.EventType", "EventType")
                        .WithMany("Bookings")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventEaseVMS.Models.Venue", "Venue")
                        .WithMany("Bookings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventEaseVMS.Models.EventType", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventEaseVMS.Models.Venue", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
